if: tag IS blank
os:
  - linux
sudo: false
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
  - lts/*
cache:
  yarn: true
before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash'
  - 'export PATH="$HOME/.yarn/bin:$PATH"'
  - yarn -v
install:
  - yarn install
jobs:
  include:
    - stage: lint
      script: yarn lint
    - name: '@applitools/eyes-common'
      script: 'cd packages/eyes-common; yarn test:unit'
      stage: unit tests
    - name: '@applitools/eyes-sdk-core'
      script: 'cd packages/eyes-sdk-core; yarn test:unit'
    - name: '@applitools/eyes-selenium'
      script: 'cd packages/eyes-selenium; yarn test:unit'
    - name: '@applitools/eyes-testcafe'
      script: 'cd packages/eyes-testcafe; yarn test:unit'
    - name: '@applitools/visual-grid-client'
      script: 'cd packages/visual-grid-client; yarn test:unit'
    - name: '@applitools/dom-utils'
      script: 'cd packages/dom-utils; yarn test:it'
      stage: end-to-end tests
    - name: '@applitools/eyes-images'
      script: 'cd packages/eyes-images; yarn test:it'
    - name: '@applitools/eyes-selenium'
      script: 'cd packages/eyes-selenium; yarn test:it'
    - name: '@applitools/eyes-testcafe'
      script: 'cd packages/eyes-testcafe; yarn test:it'
    - name: '@applitools/visual-grid-client'
      script: 'cd packages/visual-grid-client; yarn test:it'
notifications:
  slack:
    secure: >-
      oV4UyGK1CocNQmhUX0878NtkxgsJisAZsJVwZe7mFfsy0MhcRyQuk4Bux7acDr/hsm6zUepCUwEoJJhA7PFTSmqHQyHko4S1JDBAa70U+R4/b+KFUEzH9bEQC1PjLcA5G1uhqT35Q2ppTcjl64HWudVIDNi09+PAyYR/M2MSf29b1Uji0CLOUchpZk13OKeU1M5I/OhJiyq92wHRKb6WiimvsnorvozLJhqAvPgzCOxxy6tSoqSBuPffTUEC0+Qwc4A3lRai8MypppDl5pqM4bTsL0uwXIQEX5VDr0HK0kQwgkHGAFzUjg4JOrCxVxQY9kGwiymJU8JbkkPMc0QIWjV73wVITzSGz2qHMCmpyAky+mLNxYrZ8SbadrO6g7r2bgp0uQOfzB7TktDIT0/gQriw+tovkda5xoyp6YQFHHtIu/KjD2PnCymXJH43kjwcXcRHapG8RJpJjlNinEQ+FxHgU059Kebjk9/Qpnx016Q54PgO/mP1JG8OnslZkvIVPfB20K+VMnAGr3z7xek0bqJcD2439MzQulyL/60nqPqM6JBdL6oh6BxuBpAY7v9Bk+KkLHpwu6DOzmgRn6r0cc75ep2lAKS5HPW2FVFwve9poeQpwkuNna1qoqDM5ezWo7S8WJ1KMT/kaTwprqxcRAKk3iFhaTSny6m4O4qpQqk=
