# don't build tags, it's redundant
if: tag IS blank

sudo: false

git:
  depth: 3

addons:
  chrome: stable
  firefox: latest

language: node_js

os:
  - linux

node_js:
- "node"
- "lts/*"
- "8"

cache: npm

install:
  - npm install

stages:
  - lint
  - test
  - "Integration tests"
  - name: "End-to-end tests"
    if: branch = master

script:
  - npm run test:unit

jobs:
  include:
    - stage: lint
      node_js: "lts/*"
      script: npm run lint
    - stage: "Integration tests"
      node_js: "8"
      script: npm run test:it
    - stage: "End-to-end tests"
      node_js: "8"
      script: npm run test:e2e
