function createJestTestFileString(emittedTest) {
  return `// Generated by sdk-test-kit
describe('Coverage Tests', () => {
  beforeEach(async () => {
    ${emittedTest.body.setup}
  })
  afterEach(async () => {
    ${emittedTest.body.cleanup}
  })
  it('${emittedTest.name}', async () => {
    ${emittedTest.body.commands.join('\n    ')}
  })
})`
}

function createTestFileString(emittedTest, testFrameworkTemplate = createJestTestFileString) {
  return testFrameworkTemplate(emittedTest)
}

module.exports = {
  createTestFileString,
}
